### ISSUE TITLE
error when running the codes

### ISSUE THREAD

**Issue by Spatial-R** [tjhladish/dengue#2]
Hello, thanks for the codes. i used the following command to run the codes:
make model
./model -locfile locations-bangphae.txt -netfile network-bangphae.txt -popfile population-bangphae.txt -immfile immunity-bangphae.txt -mosquitomove 0.15 -mosquitoteleport 0.01 -betapm 0.1 -betamp 0.25 -mosquitomultipliers 12 31 0.11 28 0.09 31 0.20 30 0.30 31 0.83 30 1.00 31 0.50 31 0.37 30 0.38 31 0.26 30 0.30 31 0.19 -primarypathogenicity 1.0 0.25 1.0 0.25 -secondaryscaling 1.0 1.0 1.0 1.0 -mosquitocapacity 42 -runlength 364 -dailyexposed 2 2 2 2 -daysimmune 365  -prevaccinate 0.30 -ves 0.7 -peoplefile people-output-bangphaeseasonal-vac30-ves70.csv -dailyfile daily-output-bangphaeseasonal-vac30-ves70.csv > output-bangphaeseasonal-vac30-ves70.csv 

However, the model have failed with "Unknown option: -primarypathogenicity". How can i solve this problem?

**Comment by tjhladish** [comment]
In general, we have moved away from specifying command-line arguments to set parameters.  While it is still possible to run the model this way, we have not done so in years, and support for command line arguments will likely be removed in the future.  There are just too many parameters that can be set, and reading and editing them this way is cumbersome and error-prone.

The documentation that you read to find that example accompanied the initial commit for this repository.  Thus, one option would be to check out the initial commit, and work with that, and then the command you tried to run should work.

Another option is to keep using the current version of the repository, but parameterize the model similarly to how we use it.  The main function you're running by executing the "model" program is in driver.cpp.  On line 6, which is currently blank, you can start setting parameter values.  Possible parameters to set are listed in Parameters.h, specifically the public data members of the Parameters class.  For example, you can enter
`par->betaPM = 0.1;`
`par->betaMP = 0.25;`
`par->basePathogenicity = 0.6; // average pathogenicity of secondary infections`
`par->primaryRelativeRisk = 0.1; // how much less pathogenic are primary infections relative to secondary`

The last two lines shows how the primary pathogenicity and secondary scaling parameters have been replaced.

If you are interested in the details of how we parameterize the model, there is an extensive discussion in the supplement of [this paper](http://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0004661).

Best wishes,
Tom
